spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cards
    username: test
    password: test
  jpa:
    show-sql: true

server:
  error:
    include-message: always

app.jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app-jwt-expiration-milliseconds: 604800000

springdoc:
  api-docs:
    path: /api-docs