version: '3.3'
services:
  db:
    image: mysql
    container_name: db
    network_mode: "host"
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'cards'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'

  cards:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: cards:1.0
    network_mode: "host"
    ports:
      - '8080:8080'
    environment:
      WAIT_HOSTS: localhost:3306
      WAIT_TIMEOUT: 45
      WAIT_AFTER: 5
    depends_on:
      - db
